volumes:
    postgres-data:

services:
    db:
        image: postgres:15
        container_name: db
        ports:
            - '5432:5432'
            - '15432:15432'
        volumes:
            - postgres-data:/var/lib/pgsql/data
        environment:
            POSTGRES_DB: development
            POSTGRES_USER: db-user
            POSTGRES_PASSWORD: 1234
            PGDATA: /var/lib/pgsql/data

    adminer:
        image: adminer
        container_name: db-adminer
        restart: always
        ports:
            - '20080:8080'
        links:
            - db:db.docker
